# use a node base image
FROM node:latest

# set maintainer
LABEL maintainer "chandankumar.na@gmail.com"

# set a health check
HEALTHCHECK --interval=5s \
            --timeout=5s \
            CMD curl -f http://192.168.56.1 || exit 1

# tell docker what port to expose
EXPOSE 5000



# FROM node:latest

# # Create app directory
# WORKDIR /usr/src/app

# # Install app dependencies
# # A wildcard is used to ensure both package.json AND package-lock.json are copied
# # where available (npm@5+)
# COPY package*.json ./

# RUN npm install
# # If you are building your code for production
# # RUN npm ci --only=production

# # Bundle app source
# COPY . .

# EXPOSE 5000
# CMD [ "npm", "start" ]