# use a node base image
FROM node:latest

# set maintainer
LABEL maintainer "chandankumar.na@gmail.com"

# set a health check
HEALTHCHECK --interval=5s \
            --timeout=5s \
            CMD curl -f http://10.117.100.82:5000 || exit 1

# tell docker what port to expose
EXPOSE 5000
